sudo: false
language: ruby
rvm:
- 2.5.1
cache: bundler
before_install:
- gem install bundler -v 1.16.1
<% if (useDatabase) { -%>
before_script:
- psql -c 'create database courier_<%= appName %>_test;' -U postgres
- DATABASE_URL="postgres:///courier_<%= appName %>_test" bundle exec rake db:migrate
services:
- postgresql
addons:
  postgresql: '9.6'
<% } -%>
