source 'https://rubygems.org'
ruby '<%= rubyVersion %>'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'courier-service', github: 'mjm/courier-service'
gem 'jwt'
<% if (useDatabase) { -%>
gem 'pg'
<% } -%>
gem 'puma'
gem 'rack'
gem 'rack-parser'
gem 'rake', '~> 10.0'
gem 'rdiscount'
<% if (useDatabase) { -%>
gem 'sequel'
<% } -%>
<% if (useSidekiq) { -%>
gem 'sidekiq'
<% } -%>
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib'

group :development do
  gem 'pry'
end

group :test do
  gem 'rack-test'
  gem 'rspec', '~> 3.0'
<% if (useSidekiq) { -%>
  gem 'rspec-sidekiq'
<% } -%>
end
